# Generated by Django 4.2.28 on 2026-02-28 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civic_saathi', '0008_smart_hash_duplicate_detection'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ASSIGNMENT', 'New Complaint Assignment'), ('REASSIGNMENT', 'Complaint Reassigned'), ('SLA_WARNING', 'SLA Deadline Warning'), ('ESCALATION', 'Complaint Escalated')], default='ASSIGNMENT', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_notifications', to='civic_saathi.complaint')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='civic_saathi.worker')),
            ],
            options={
                'verbose_name': 'Worker Notification',
                'verbose_name_plural': 'Worker Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
